window.addEventListener("scroll", function(){
    var navbar = document.querySelector(".header")
    var nav_button1 = document.querySelector(".nav_btn1")
    var nav_button2 = document.querySelector(".nav_btn2")
    var nav_button3 = document.querySelector(".nav_btn3")
    var nav_button4 = document.querySelector(".nav_btn4")
    var nav_button5 = document.querySelector(".nav_btn5")
    var nav_button6 = document.querySelector(".nav_btn6")
    var logo = document.querySelector(".logo")
    var logo2 = document.querySelector(".logo2")
    var seacrh = document.querySelector(".link-search")
    navbar.classList.toggle('sticky', window.scrollY > 0)
    nav_button1.classList.toggle('sticky_button1', window.scrollY > 0)
    nav_button2.classList.toggle('sticky_button2', window.scrollY > 0)
    nav_button3.classList.toggle('sticky_button3', window.scrollY > 0)
    nav_button4.classList.toggle('sticky_button4', window.scrollY > 0)
    nav_button5.classList.toggle('sticky_button5', window.scrollY > 0)
    nav_button6.classList.toggle('sticky_button6', window.scrollY > 0)
    logo.classList.toggle('sticky_logo1', window.scrollY > 0)
    logo2.classList.toggle('sticky_logo2', window.scrollY > 0)
    search.classList.toggle('search_button', window.scrollY > 0)
})